// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcbId4lgeDjevb--pay8L79dTStAtD1eM',
    appId: '1:709830412742:web:69a845d1ff931fedca0ac7',
    messagingSenderId: '709830412742',
    projectId: 'nutricode-81ad6',
    authDomain: 'nutricode-81ad6.firebaseapp.com',
    storageBucket: 'nutricode-81ad6.firebasestorage.app',
    measurementId: 'G-W3GGJ7NB3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_zt1GpwFW5zwlJ0N414VMTCetSkDl2PM',
    appId: '1:709830412742:android:abe379e216738b3dca0ac7',
    messagingSenderId: '709830412742',
    projectId: 'nutricode-81ad6',
    storageBucket: 'nutricode-81ad6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0g3Ii5H2zuThfKWsr9uDXHOp6jAwpk-I',
    appId: '1:709830412742:ios:eb94d1949ac5a6b3ca0ac7',
    messagingSenderId: '709830412742',
    projectId: 'nutricode-81ad6',
    storageBucket: 'nutricode-81ad6.firebasestorage.app',
    iosBundleId: 'com.nutricode.nutricodePrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0g3Ii5H2zuThfKWsr9uDXHOp6jAwpk-I',
    appId: '1:709830412742:ios:eb94d1949ac5a6b3ca0ac7',
    messagingSenderId: '709830412742',
    projectId: 'nutricode-81ad6',
    storageBucket: 'nutricode-81ad6.firebasestorage.app',
    iosBundleId: 'com.nutricode.nutricodePrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcbId4lgeDjevb--pay8L79dTStAtD1eM',
    appId: '1:709830412742:web:434afe4f00170147ca0ac7',
    messagingSenderId: '709830412742',
    projectId: 'nutricode-81ad6',
    authDomain: 'nutricode-81ad6.firebaseapp.com',
    storageBucket: 'nutricode-81ad6.firebasestorage.app',
    measurementId: 'G-QNCR7W89KB',
  );
}
